version: '3'

services:
  app:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: always
    ports:
      - '20400:80'
    volumes:
      - "/:/srv"
    environment:
      - PUID=0
      - PGID=0