version: '3'

services:
  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - 8186:3306
    volumes:
      - /mnt/ExtData/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=20154530
      - MYSQL_PASSWORD=20154530
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - 8180:80
    links:
      - db
    volumes:
      - /mnt/ExtData/nextcloud:/var/www/html
      - type: bind
        source: /mnt/ExtData/download
        target: /download
    environment:
      - MYSQL_PASSWORD=20154530
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db